repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ^vendor/
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.38.0
    hooks:
      - id: golangci-lint
